# Get Started {-}


## Start Git {-}

Git is a version control system (VCS), head to [Version Control with Git] for the full background, training, and reference materials. 

We recommend that Git is used along with a hosting repository, such as GitHub (or Gitea, GitLab, etc.) and that the [Git Flow] is followed. However, Git can be used locally while working on a project. The steps outlined here are for this purpose and should only be followed for a personal project that is **local or on your personal network folder**. For collaborative work, see the getting started section for [Start GitHub].

Throughout the guide, `<...>` has been used to indicate text which is user specific and should be edited with your own details. 


### Initial Setup {-}

These intructions should only need to be followed once or when setting up a new device.

1. **Install Git** - Git is a free, open-source, software available from https://git-scm.com/. If you work within Public Health & Intelligence, request the software from IT through the [Service Portal](https://nhsnss.service-now.com/sp). Once authorised, this will allow you to download it from the Software Center on your machine. 

2. **Configure your details** - Git needs to know who you are, use the following commands to configure your username and email:

* `git config --global user.email <NHS email address>`
* `git config --global user.name <your name>`

At any time you can check what the current user details are using:

* `git config --global user.email`


### Project Steps {-}

1. **Navigate to the directory** - navigate to the project folder on the shell command line, see [The Shell] for the background, training, and reference materials on the Shell command line. You can also navigate the project folder using Windows Explorer, right click, and select "Git Bash Here", this will open a command-line interface for that folder. From here, you can use Git and shell commands. *The line prompt for the user to enter commands is `$`, other lines are generated by the Shell.*

```
username@NSS000000 MINGW64 ~
$ cd Documents/project

username@NSS000000 MINGW64 ~Documents/project
$
```

2. **Initialise Git** - in the command line enter `git init`. Git is now initialised inside that project folder/directory and can track any files or sub-folders.

```
username@NSS000000 MINGW64 ~/Documents/project
$ git init
Initialized empty Git repository in C:/Users/username/Documents/project/.git/

username@NSS000000 MINGW64 ~/Documents/project (master)
$ 
```
You'll notice that you're on the "*master*" branch. For set-up purposes, we'll continue to work on the *master* branch but note that it's best practice to do any work in a separate branch which is later merged into the *master* when ready.

3. **Check for changes** - Git will recongise any files that have been added or changed. Enter `git status` to see an overview. 

```
username@NSS000000 MINGW64 ~/Documents/project (master)
$ git status
On branch master

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)
    
      .gitignore
      project.Rproj
      
nothing added to commit but untracked files present (use "git add" to track)

username@NSS000000 MINGW64 ~/Documents/project (master)
$
```
In this example, an R Project has been started with a .gitignore file. *A .gitignore file is used to tell Git which files and folders to ignore, this is particularly imporant when working with GitHub and ensures that no sensitive information or data files are uploaded to GitHub. An example .gitignore file can be found [here](https://github.com/NHS-NSS-transforming-publications/GitHub-guidance/blob/master/.gitignore). Be aware that other file formats may also need to be considered to be added in this file.*

4. **Track files** - in this example Git has recognised two untracked files. In order to track them we must first *stage* them using `git add <file name>` (if the file name contains spaces you will need to put single quotation marks around it, e.g. `'file name'`) You can stage each file individually or use `git add .` to stage all files which have been detected by Git. **It is usually safer to stage each file separately.**

```
username@NSS000000 MINGW64 ~/Documents/project (master)
$ git add .gitignore

username@NSS000000 MINGW64 ~/Documents/project (master)
$ git add project.Rproj

username@NSS000000 MINGW64 ~/Documents/project (master)
$ git status
On branch master

No commits yet

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)
      
      new file:   .gitignore
      new file:   project.Rproj
 
   
username@NSS000000 MINGW64 ~/Documents/project (master)
$
```

5. **Commit changes** - now, a set of staged changes can be committed using `git commit -m <commit message>`. When entering you commit message, ensure that it's consise, meaningful and written in imperative mode.

```
username@NSS000000 MINGW64 ~/Documents/project (master)
$ git commit -m "Create R project"
[master (root-commit) 1ab2cde] Create R project
  2 files changed, 17 insertions(+)
  create mode 100644 .gitignore
  create mode 100644 project.Rproj
  
username@NSS000000 MINGW64 ~/Documents/project (master)
$
```
Git has now stored a snapshot of the project folder and its content at that point in time. Going forward, it will now be possible to check back through the old version of the folder via the commits and, if necessary, revert to a previous version. To see a history of ocmmits on a branch use `git log`.

6. **Create a branch** - when first created, a branch is an exact copy of the original folder and contents (the master branch). As you work on the project, the working branch will change but leave the master branch untouched. This means that you always retain a master copy of the project and you only merge changes when you're satisfied that they're ready. To create a branch use `git branch <name of branch>`. To switch to working on the new working branch, use `git checkout <name of branch>`. These two steps can be done via one command, `git checkout -b <name of branch`.

```
username@NSS000000 MINGW64 ~/Documents/project (master)
$ git checkout -b feature
Switched to branch 'feature'

username@NSS000000 MINGW64 ~/Documents/project (feature)
$
```

7. **Check for changes to branch** - like in step 3, you'll do work in your project and have changes to commit, use `git status` as before to see an overview. Then, keep saving and committing your work using `git add <file>` and `git commit -m <commit message>`.

```
username@NSS000000 MINGW64 ~/Documents/project (feature)
$ git status
On branch feature
Changes not staged for commit:
  (use "git add <file>..." to include in what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)
  
      modified:   script.R
      
no changes added to commit (use "git add" and/or "git commit -a")

username@NSS000000 MINGW64 ~/Documents/project (feature)
$ git add script.R

username@NSS000000 MINGW64 ~/Documents/project (feature)
$ git commit -m "Set up new script"
[feature a1bc23d] Set up new script
  1 file changed, 1 insertion(+)
```

8. **Check for branch differences** - when you want to merge the changes into the master branch, you'll want to compare them first. You can see the changes made by using `git diff <master branch> <working branch>`. On the command line, insertions have plus (`+`) signs at the start of the line while any deletions will have a negative (`-`) sign.

```
username@NSS000000 MINGW64 ~/Documents/project (feature)
$ git checkout master
Switched to branch 'master'

username@NSS000000 MINGW64 ~/Documents/project (master)
$ git diff master feature
diff --git a/script.R b/script.R
new file modile 100644
index 0000000..fe32d10
--- /dev/null
+++ b/script.R
@@ -0,0 +1,1 @@
+ #This is a demo R script with no content
\ No newline at end of file

username@NSS000000 MINGW64 ~/Documents/project (master)
$
```

9. **Merge changes into master branch** - when you're ready to make the merge into the master branch, ensure you're on the master branch and use `git merge <working branch>`.

```
username@NSS000000 MINGW64 ~/Documents/project (master)
$ git merge feature
Updating 111abc0..f999ed0
Fast-forward
  script.R | 1 +
  1 file changed, 1 insertion (+)
  create mode 100644 script.R
  
username@NSS000000 MINGW64 ~/Documents/project (master)
$
```

10. **Delete working branch** - when you're finished with your working branch delete it using `git branch -d <branch name>`, this will help to avoid merge conflicts. There is no need to have long-living branches; when you want to make further changes to your project, simply create a new working branch. 


### Top Tips

These are some tips/references to keep in mind when working with Git:

* See [Git Command Reference] for a full list of commands that can be used in Git.
* Although it's good to use version control throughout a project, Git can be initialised on an exisitng project folder.
* Commit often. Commits are the project history so commit after a section of code is completed, before lunch, at the end of the day, etc.
* [Write good commit messages](https://github.com/erlang/otp/wiki/writing-good-commit-messages). The messages should be succint, meaningful, and written in imperative form (i.e. "Add x, y, z" not "Added x, y, z").
* Delete branches after merging. This reduces risks of merge conflicts and keeps your work set-up tidy.
* It's possible to have multiple branches for working on or fixing multiple features of your project, but be aware that this increases the chance of a merge conflict.
* See [Merge Conflicts] for more information about what they are, and how to avoid/resolve them.


## Start GitHub {-}

GitHub is a Git hosting repository that provides users with tools to ship better code through command line features, issues (threaded discussions), pull requests, and code review. GitHub builds collaboration directly into the development process. Work is organised into repositories, where users can outline requirements or direction and set expectations for team members. Then, using the [GitHub Flow], developers simply create a branch to work on updates, commit changes to save them, open a pull request to propose and dicsuss changes, and merge pull requests once everyone is on the same page. See [GitHub Workflow] for more details.


### GitHub Flow




## Start RStudio Integration {-}