# Git Cheat Sheet {-}

### Git Basics {-}

```{r, echo=FALSE}
knitr::kable(
  data.frame(
    "Command" = c("`git init [directory]` ", "`git clone [repo]` ", "`git config user.name [name]` ", "`git add [directory]` ", "`git commit -m “[message]”` ", "`git status` ", "`git log` ", "`git diff` "),
    "Description" = c("Create empty Git repo in specified directory. Run with no arguments to initialise the current directory as a git repository. ", "Clone repo located at `[repo]` onto local machine. Original repo can be located on the local file system or on a remote machine via HTTP or SSH. ", "Define author name to be used for all commits in current repo. Devs commonly use `--global` flag to set config options for current user. ", "Stage all changes in `[directory]` for the next commit. Replace `[directory]` with a `[file]` to change a specific file. ", "Commit the staged snapshot, but instead of launching a text editor, use [message] as the commit message. ", "List which files are staged, unstated, and untracked. ", "Display the entire commit history using the default format. For customisation see additional options. ", "Show unstated changes between your index and working directory. ")
  )
)
```

&nbsp;


### Undoing changes {-}

```{r, echo=FALSE}
knitr::kable(
  data.frame(
    "Command" = c("`git revert [commit]` ", "`git reset [file]` ", "`git clean -n` "),
    "Description" = c("Create new commit that undoes all of the changes made in `[commit]`, then apply it to the current branch. ", "Remove `[file]` from the staging area, but leave the working directory unchanged. This un-stages a file without overwriting any changes. ", "Shows which files would be removed from working directory. Use the `-f` flag in place of the `-n` flag to execute the clean. ")
  )
)
```

&nbsp;


### Rewriting Git History {-}

```{r, echo=FALSE}
knitr::kable(
  data.frame(
    "Command" = c("`git commit —amend` ", "`git rebase [base]` ", "`git reflog` "),
    "Description" = c("Replace the last commit with the staged changes and last commit combined. Use with nothing staged to edit the last commit’s message. ", "Rebase the current branch onto `[base]`. `[base]` can be a commit ID, a branch name, a tag, or a relative reference to `HEAD`. ", "Show a log of changes to the local repository’s `HEAD`. Add `--relative-date` flag to show date info or `--all` to show all refs. ")
  )
)
```

&nbsp;


### Git Branches {-}

```{r, echo=FALSE}
knitr::kable(
  data.frame(
    "Command" = c("`git branch` ", "`git checkout -b [branch]` ", "`git merge [branch]` "),
    "Description" = c("List all of the branches in your repo. Add a `branch` argument to create a new branch with the name `branch`. ", "Create and check out a new branch named `[branch]`. Drop the `-b` flag to checkout an existing branch. ", "Merge `[branch]` into the current branch. ")
  )
)
```

&nbsp;


### Remote Repositories {-}

```{r, echo=FALSE}
knitr::kable(
  data.frame(
    "Command" = c("`git remote add [name] [url]` ", "`git fetch [remote] [branch]` ", "`git pull [remote]` ", "`. git push [remote] [branch]` "),
    "Description" = c("Create a new connection to a remote repo. After adding a remote, you can use `[name]` as a shortcut for `[url]` in other commands. ", "Fetches a specific `[branch]`, from the repo. Leave off `[branch]` to fetch all remote refs. ", "Fetch the specified remote’s copy of current branch and immediately merge it into the local copy. ", "Push the branch to `[remote]`, along with necessary commits and objects. Creates named branch in the remote repo if it doesn’t exist. ")
  )
)
```

&nbsp;


### Git Config {-}

```{r, echo=FALSE}
knitr::kable(
  data.frame(
    "Command" = c("`git config --global user.name [name]` ", "`git config --global user.email [email]` ", "`git config --global alias. [alias-name] [git-commands]` ", "`git config --system core.editor [editor]` ", "`git config --global --edit` "),
    "Description" = c("Define the author name to be used for all commits by the current user. ", "Define the author email to be used for all commits by the current user. ", "Create shortcut for a Git command. E.g. `alias.glog log --graph --oneline` will set `git glog` equivalent to `git log --graph --oneline`. ", "Set text editor used by commands for all users on the machine. `[editor]` arg should be the command that launches the desired editor (e.g., vi). ", "Open the global configuration file in a text editor for manual editing. ")
  )
)
```

&nbsp;


### Git Log {-}

```{r, echo=FALSE}
knitr::kable(
  data.frame(
    "Command" = c("`git log -[limit]` ", "`git log --oneline` ", "`git log -p` ", "`git log —-stat` ", "`git log —-author= ”[pattern]”` ", "`git log —grep=”[pattern]”` ", "`git log [since]..[until]` ", "`git log -- [file]` ", "`git log --graph --decorate` "),
    "Description" = c("Limit number of commits by `[limit]`. E.g. `git log -5` will limit to 5 commits. ", "Condense each commit to a single line. ", "Display the full diff of each commit. ", "Include which files were altered and the relative number of lines that were added or deleted from each of them. ", "Search for commits by a particular author. ", "Search for commits with a commit message that matches [pattern]. ", "Shows commits that occur between `[since]` and `[until]`. Args can be a commit ID, branch name, `HEAD`, or any other kind of revision reference. ", "Only display commits that have the specified file. ", "`--graph` flag draws a text based graph of commits on left side of commit msgs. `--decorate` adds names of branches or tags of commits shown. ")
  )
)
```

&nbsp;


### Git Diff {-}

```{r, echo=FALSE}
knitr::kable(
  data.frame(
    "Command" = c("`git diff HEAD` ", "`git diff --cached` "),
    "Description" = c("Show difference between working directory and last commit. ", "Show difference between staged changes and last commit. ")
  )
)
```

&nbsp;


### Git Reset {-}

```{r, echo=FALSE}
knitr::kable(
  data.frame(
    "Command" = c("`git reset` ", "`git reset --hard` ", "`git reset [commit]` ", "`git reset --hard [commit]` "),
    "Description" = c("Reset staging area to match most recent commit, but leave the working directory unchanged. ", "Reset staging area and working directory to match most recent commit and *overwrites all changes* in the working directory. ", "Move the current branch tip backward to `[commit]`, reset the staging area to match, but leave the working directory alone. ", "Same as previous, but resets both the staging area & working directory to match. Deletes uncommitted changes, and all commits after `[commit]`. ")
  )
)
```

&nbsp;


### Git Rebase {-}

```{r, echo=FALSE}
knitr::kable(
  data.frame(
    "Command" = c("`git rebase -i [base]`"),
    "Description" = c("Interactively rebase current branch onto `[base]`. Launches editor to enter commands for how each commit will be transferred to the new base. ")
  )
)
```

&nbsp;


### Git Pull {-}

```{r, echo=FALSE}
knitr::kable(
  data.frame(
    "Command" = c("`git pull --rebase [remote]`"),
    "Description" = c("Fetch the remote’s copy of current branch and rebases it into the local copy. Uses git rebase instead of merge to integrate the branches. ")
  )
)
```

&nbsp;


### Git Push {-}

```{r, echo=FALSE}
knitr::kable(
  data.frame(
    "Command" = c("`git push [remote] --force` ", "`git push [remote] --all` ", "`git push [remote] --tags` "),
    "Description" = c("Forces the `git push` even if it results in a non-fast-forward merge. Do not use the `--force` flag unless you’re absolutely sure you know what you’re doing. ", "Push all of your local branches to the specified remote. ", "Tags aren’t automatically pushed when you push a branch or use the —all flag. The —tags flag sends all of your local tags to the remote repo. ")
  )
)
```

&nbsp;

